apiVersion: 1
datasources:
- name: prometheus
  type: prometheus
  uid: P1809F7CD0C75ACF3
  url: http://aprom:9090
  access: proxy
  basicAuth: false
  isDefault: true
  jsonData:
    timeInterval: '5s'
- name: alertmanager
  type: alertmanager
  orgId: 1
  typeLogoUrl: public/img/icn-datasource.svg
  access: proxy
  url: http://127.0.0.1:9093
  password: 
  user: 
  database: 
  basicAuth: 
  isDefault: false
  jsonData:
    implementation: 'prometheus'
