global:
  resolve_timeout: 3m

route:
  group_by: ['alertname', 'cluster', 'job', 'severity']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h
  receiver: 'telegram-notifications'

receivers:
- name: 'telegram-notifications'
  telegram_configs:
  - bot_token: '8545467752:AAEV53fhvSM46VBpoxFIrCu97ICobrHKEH4'
    chat_id: 1629276260
    send_resolved: true
    parse_mode: 'HTML'
    message: |
      {{ if eq .Status "firing" }}🔥 <b>[CẢNH BÁO SỰ CỐ HỆ THỐNG]</b>{{ else }}✅ <b>[SỰ CỐ ĐÃ ĐƯỢC KHẮC PHỤC]</b>{{ end }}
      <b>Tên lỗi:</b> {{ if .CommonLabels.alertname }}{{ .CommonLabels.alertname }}{{ else }}{{ (index .Alerts 0).Labels.alertname }}{{ end }}
      <b>Mức độ:</b> {{ if .CommonLabels.severity }}{{ .CommonLabels.severity }}{{ else if (index .Alerts 0).Labels.severity }}{{ (index .Alerts 0).Labels.severity }}{{ else }}info{{ end }}
      <b>Dịch vụ:</b> {{ if .CommonLabels.job }}{{ .CommonLabels.job }}{{ else if (index .Alerts 0).Labels.job }}{{ (index .Alerts 0).Labels.job }}{{ else }}scylla_cluster{{ end }}{{ if or .CommonLabels.instance (index .Alerts 0).Labels.instance }} ({{ if .CommonLabels.instance }}{{ .CommonLabels.instance }}{{ else }}{{ (index .Alerts 0).Labels.instance }}{{ end }}){{ end }}
      <b>Chi tiết:</b> {{ if .CommonAnnotations.summary }}{{ .CommonAnnotations.summary }}{{ else if .CommonLabels.summary }}{{ .CommonLabels.summary }}{{ else if (index .Alerts 0).Annotations.summary }}{{ (index .Alerts 0).Annotations.summary }}{{ else if (index .Alerts 0).Labels.summary }}{{ (index .Alerts 0).Labels.summary }}{{ else }}Không có chi tiết{{ end }}
      <b>Mô tả:</b> {{ if .CommonAnnotations.description }}{{ .CommonAnnotations.description }}{{ else if .CommonLabels.description }}{{ .CommonLabels.description }}{{ else if (index .Alerts 0).Annotations.description }}{{ (index .Alerts 0).Annotations.description }}{{ else if (index .Alerts 0).Labels.description }}{{ (index .Alerts 0).Labels.description }}{{ else }}Không có mô tả{{ end }}
      <b>Thời gian:</b> {{ (index .Alerts 0).StartsAt.Local.Format "15:04:05 02/01/2006" }}
